// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripPlannerAPI.Data;

#nullable disable

namespace TripPlannerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b09e8b1f-684b-48a7-addb-6d74b8c3dccc",
                            ConcurrencyStamp = "45da5b93-5a5d-4281-8cec-872b23f90817",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3f53328b-52af-4f47-9829-67bcd9ecce7a",
                            ConcurrencyStamp = "36f59bd5-53c6-423d-95a2-24ef073b3ee9",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Location", b =>
                {
                    b.Property<int>("locationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("lat")
                        .HasColumnType("REAL");

                    b.Property<float>("lng")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("locationId");

                    b.HasIndex("tripId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Pin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Lat")
                        .HasColumnType("REAL");

                    b.Property<float>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("tripId");

                    b.ToTable("Pin");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Post", b =>
                {
                    b.Property<int>("postId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RelatedTriptripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("postId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RelatedTriptripId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Preference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("preferenceStr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("tripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("tripId");

                    b.ToTable("Preference");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.PreferenceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferenceTypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PreferenceType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PreferenceTypeName = "Entertainment"
                        },
                        new
                        {
                            Id = 2,
                            PreferenceTypeName = "Sightseeing"
                        },
                        new
                        {
                            Id = 3,
                            PreferenceTypeName = "Exploring"
                        },
                        new
                        {
                            Id = 4,
                            PreferenceTypeName = "Culture"
                        },
                        new
                        {
                            Id = 5,
                            PreferenceTypeName = "History"
                        },
                        new
                        {
                            Id = 6,
                            PreferenceTypeName = "Free ride"
                        },
                        new
                        {
                            Id = 7,
                            PreferenceTypeName = "Training"
                        },
                        new
                        {
                            Id = 8,
                            PreferenceTypeName = "Nature"
                        });
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOrganizer")
                        .HasColumnType("INTEGER");

                    b.Property<float>("RatingPoints")
                        .HasColumnType("REAL");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Trip", b =>
                {
                    b.Property<int>("tripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("creationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("creatorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("distance")
                        .HasColumnType("REAL");

                    b.Property<bool>("isRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<float>("totalTime")
                        .HasColumnType("REAL");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("tripId");

                    b.HasIndex("creatorId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.TripType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TripType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeName = "car"
                        },
                        new
                        {
                            Id = 2,
                            TypeName = "bike"
                        },
                        new
                        {
                            Id = 3,
                            TypeName = "foot"
                        });
                });

            modelBuilder.Entity("TripPlannerAPI.Models.TripTypePreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferenceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreferenceTypeId");

                    b.HasIndex("TripTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("TripTypesPreferences");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<float>("OrganizerRating")
                        .HasColumnType("REAL");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<float>("UserRating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TripUser", b =>
                {
                    b.Property<int>("FavoriteTripstripId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FavoritedById")
                        .HasColumnType("TEXT");

                    b.HasKey("FavoriteTripstripId", "FavoritedById");

                    b.HasIndex("FavoritedById");

                    b.ToTable("TripUser");
                });

            modelBuilder.Entity("TripUser1", b =>
                {
                    b.Property<int>("TripsJoinedtripId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("membersId")
                        .HasColumnType("TEXT");

                    b.HasKey("TripsJoinedtripId", "membersId");

                    b.HasIndex("membersId");

                    b.ToTable("TripUser1");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlannerAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Location", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.Trip", null)
                        .WithMany("waypoints")
                        .HasForeignKey("tripId");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Pin", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.Trip", null)
                        .WithMany("Pins")
                        .HasForeignKey("tripId");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Post", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("TripPlannerAPI.Models.Trip", "RelatedTrip")
                        .WithMany()
                        .HasForeignKey("RelatedTriptripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("RelatedTrip");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Preference", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.Trip", null)
                        .WithMany("preferences")
                        .HasForeignKey("tripId");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Rating", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Trip", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.User", "creator")
                        .WithMany("CreatedTrips")
                        .HasForeignKey("creatorId");

                    b.Navigation("creator");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.TripTypePreference", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.PreferenceType", "PreferenceType")
                        .WithMany()
                        .HasForeignKey("PreferenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlannerAPI.Models.TripType", "TripType")
                        .WithMany()
                        .HasForeignKey("TripTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlannerAPI.Models.User", "User")
                        .WithMany("TripTypesPreferences")
                        .HasForeignKey("UserId");

                    b.Navigation("PreferenceType");

                    b.Navigation("TripType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripUser", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("FavoriteTripstripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlannerAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FavoritedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripUser1", b =>
                {
                    b.HasOne("TripPlannerAPI.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripsJoinedtripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlannerAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("membersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlannerAPI.Models.Trip", b =>
                {
                    b.Navigation("Pins");

                    b.Navigation("preferences");

                    b.Navigation("waypoints");
                });

            modelBuilder.Entity("TripPlannerAPI.Models.User", b =>
                {
                    b.Navigation("CreatedTrips");

                    b.Navigation("TripTypesPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
